### ISSUE TITLE
Gitpop3 currently not working

### ISSUE THREAD

**Issue by try2codesecure** [AndreMiras/gitpop3#18]
Currently every query shows an 401:
![Bildschirmfoto_2022-02-02_16-23-09](https://user-images.githubusercontent.com/4202158/152183742-e7170e89-24cf-44cc-9ee5-516d7d75e7cc.png)

**Comment by AndreMiras** [comment]
Thanks for the report.
Yes somebody leaked my GraphQL Token so it was revoked.
I've generated a new one so it works again, but I may need to address it in a different way if that happens again.
It's a bit annoying because that may mean introducing a backend just to deal with the token.
I need to think about it
