### ISSUE TITLE
Error page on all repositories

### ISSUE THREAD

**Issue by Chaprnks** [AndreMiras/gitpop3#20]
I've been an avid user of gitpop3, but about a week ago; something broke. Now every repository searched returns this error 401 message:
![U9uzM0p](https://github.com/AndreMiras/gitpop3/assets/6340970/2b100faa-ab67-4b86-b9b7-67736a081840)

**Comment by AndreMiras** [comment]
Thanks for the report, yes I think it's because some GitHub credentials used for the search API got revoked. I'll try to find a way to solve it soon

**Comment by AndreMiras** [comment]
The way I dealt with it so far was to kinda obfuscate the key to GitHub bots so they won't revoke it, but they got smarter and caught it.
Since this is a frontend only project there's no way to not expose the key to the client.
So the only thing I could think of is making the query server side, but that would require to either introduce a backend/lambda to only deal with this aspect, but keep the rest of the code the same or completely migrate to a different solution like Next.js and use serverless/serverside for API calls. In both cases we have some type of backend, but one is simply some dumb proxy handling the auth and keeping the rest of the frontend the same (also hosted in GitHub pages) the other is a complete tech revamp using Next.js
Another solution I could explore would be to let each user authenticate using OAuth to perform the API call
